Algoritmo "Exercicio 39"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Faça um algoritmo que mostre na tela a seguinte contagem:
//10 9 8 7 6 5 4 3 Acabou!
// Autor(a)    : Izabelle
// Data atual  : 16/03/2026
Var
   contador:inteiro
Inicio
      contador<-10
      Enquanto (contador>=3) faca
               Escreva(contador,"..")
               contador<-contador-1
      FimEnquanto
      Escreva("Acabou!")
Fimalgoritmo