Algoritmo "Exercicio 38"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : 38) Escreva um programa que mostre na tela a seguinte contagem:
//6 7 8 9 10 11 Acabou!
// Autor(a)    : Izabelle
// Data atual  : 16/03/2026
Var
   contador:inteiro
Inicio
   contador <-6
   Enquanto (contador<=11) faca
   Escreva(contador,"..")
   contador <- contador +1
   FimEnquanto
   Escreva("Acabou!")
Fimalgoritmo