Algoritmo "Exercicio 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   :  Crie um aplicativo que mostre na tela a seguinte contagem:
//0 3 6 9 12 15 18 Acabou!
// Autor(a)    : Izabelle
// Data atual  : 16/03/2026
Var
contador,salto:inteiro
Inicio
      contador<-0
      salto<-3
      enquanto (contador<=18) faca
               Escreva(contador,".. ")
               contador <- contador+salto
      fimenquanto
      Escreva("Acabou!")
Fimalgoritmo