Algoritmo "Exercicio 020"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou ÍMPAR.
// Autor(a)    : Izabelle Casagrande
// Data atual  : 04/03/2026
Var

   n1:inteiro

Inicio

   Escreva("Digitre um número: ")
   Leia(n1)
   Se (n1%2=0) entao
      Escreva("O numero ",n1," é par")
   senao
        Escreva("O numero ",n1," é impar")
   FimSe

Fimalgoritmo